<script lang="ts">
  import { onMount } from 'svelte';
  import { Plus, RefreshCw, AlertTriangle, Shield, Activity } from '@lucide/svelte';
  import { impactRatingApi, SeverityLevel } from '../../api/impact-ratings';
  import type { DamageScenario } from '../../api/damage-scenarios';
  import { scopeApi, type Scope } from '../../api/scopes';
  import { safeApiCall } from '../../utils/error-handler';
  import { showSuccess, showError } from '../ToastManager.svelte';
  import ImpactRatingList from './ImpactRatingList.svelte';
  import ImpactRatingEditor from './ImpactRatingEditor.svelte';
  
  // State
  let scenarios: DamageScenario[] = [];
  let isLoading = true;
  let error = '';
  let showEditor = false;
  let selectedScenario: DamageScenario | null = null;
  
  // Data for filters
  let availableScopes: any[] = [];
  let isLoadingFilterData = false;
  
  // Filters
  let selectedScopeId: string | null = null;
  let selectedSafetyImpact: SeverityLevel | null = null;
  let selectedFinancialImpact: SeverityLevel | null = null;
  let selectedOperationalImpact: SeverityLevel | null = null;
  let selectedPrivacyImpact: SeverityLevel | null = null;
  let autoGeneratedOnly = false;
  
  // Stats
  let stats = {
    totalScenarios: 0,
    highSafetyImpact: 0,
    highFinancialImpact: 0,
    highOperationalImpact: 0,
    highPrivacyImpact: 0
  };
  
  onMount(async () => {
    // Load filter data and impact ratings in parallel
    await Promise.all([
      loadFilterData(),
      loadImpactRatings()
    ]);
  });
  
  /**
   * Load scopes for filters
   */
  async function loadFilterData() {
    isLoadingFilterData = true;
    
    try {
      const scopesResult = await safeApiCall(() => scopeApi.getAll());
      
      if (scopesResult) {
        availableScopes = scopesResult.scopes || [];
      }
    } catch (err) {
      console.error('Error loading filter data:', err);
      // Don't show error for filter data loading, as it's not critical
    } finally {
      isLoadingFilterData = false;
    }
  };
  
  async function loadImpactRatings() {
    isLoading = true;
    error = '';
    
    try {
      const result = await safeApiCall(() => impactRatingApi.listRatings({
        scope_id: selectedScopeId || undefined,
        safety_impact: selectedSafetyImpact || undefined,
        financial_impact: selectedFinancialImpact || undefined,
        operational_impact: selectedOperationalImpact || undefined,
        privacy_impact: selectedPrivacyImpact || undefined,
        auto_generated_only: autoGeneratedOnly || undefined
      }));
      
      if (result) {
        scenarios = result;
        updateStats(scenarios);
      }
    } catch (err) {
      console.error('Error loading impact ratings:', err);
      error = 'Failed to load impact ratings. Please try again.';
    } finally {
      isLoading = false;
    }
  }
  
  function updateStats(scenarios: DamageScenario[]): void {
    stats.totalScenarios = scenarios.length;
    stats.highSafetyImpact = scenarios.filter(s => 
      s.safety_impact === SeverityLevel.HIGH || s.safety_impact === SeverityLevel.CRITICAL
    ).length;
    stats.highFinancialImpact = scenarios.filter(s => 
      s.financial_impact === SeverityLevel.HIGH || s.financial_impact === SeverityLevel.CRITICAL
    ).length;
    stats.highOperationalImpact = scenarios.filter(s => 
      s.operational_impact === SeverityLevel.HIGH || s.operational_impact === SeverityLevel.CRITICAL
    ).length;
    stats.highPrivacyImpact = scenarios.filter(s => 
      s.privacy_impact === SeverityLevel.HIGH || s.privacy_impact === SeverityLevel.CRITICAL
    ).length;
  }
  
  function handleEditRatings(scenario: DamageScenario): void {
    selectedScenario = scenario;
    showEditor = true;
  }
  
  function handleEditorClose() {
    showEditor = false;
    selectedScenario = null;
    loadImpactRatings(); // Refresh the list
  }
  
  function handleFilterChange() {
    loadImpactRatings();
  }
</script>

<div class="space-y-6">
  <!-- Stats cards -->
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4 mb-8">
    <!-- Total Scenarios -->
    <div class="metric-card">
      <div class="flex items-start">
        <Shield size={24} style="color: var(--color-primary);" class="mr-3 mt-1" />
        <div>
          <p class="metric-label">Total Scenarios</p>
          <p class="metric-value">{stats.totalScenarios}</p>
        </div>
      </div>
    </div>
    
    <!-- High Safety Impact -->
    <div class="metric-card">
      <div class="flex items-start">
        <Shield size={24} style="color: var(--color-danger);" class="mr-3 mt-1" />
        <div>
          <p class="metric-label">High Safety Impact</p>
          <p class="metric-value">{stats.highSafetyImpact}</p>
        </div>
      </div>
    </div>
    
    <!-- High Financial Impact -->
    <div class="metric-card">
      <div class="flex items-start">
        <Activity size={24} style="color: var(--color-warning);" class="mr-3 mt-1" />
        <div>
          <p class="metric-label">High Financial Impact</p>
          <p class="metric-value">{stats.highFinancialImpact}</p>
        </div>
      </div>
    </div>
    
    <!-- High Operational Impact -->
    <div class="metric-card">
      <div class="flex items-start">
        <Activity size={24} style="color: var(--color-info);" class="mr-3 mt-1" />
        <div>
          <p class="metric-label">High Operational Impact</p>
          <p class="metric-value">{stats.highOperationalImpact}</p>
        </div>
      </div>
    </div>
    
    <!-- High Privacy Impact -->
    <div class="metric-card">
      <div class="flex items-start">
        <Activity size={24} style="color: var(--color-success);" class="mr-3 mt-1" />
        <div>
          <p class="metric-label">High Privacy Impact</p>
          <p class="metric-value">{stats.highPrivacyImpact}</p>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Action bar -->
  <div class="flex justify-between items-center mb-6">
    <h2 class="text-xl font-semibold" style="color: var(--color-text-main);">Impact Ratings</h2>
    
    <div class="flex space-x-2">
      <button 
        on:click={loadImpactRatings}
        class="btn btn-secondary flex items-center gap-1"
      >
        <RefreshCw size={16} />
        <span>Refresh</span>
      </button>
    </div>
  </div>
  
  <!-- Filters -->
  <div class="bg-white p-4 rounded-lg border border-gray-200 mb-6">
    <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4">
      <!-- Scope Filter -->
      <div>
        <label for="scopeFilter" class="block text-sm font-medium text-gray-700 mb-1">Scope</label>
        <select 
          id="scopeFilter"
          bind:value={selectedScopeId}
          on:change={handleFilterChange}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
        >
          <option value={null}>All Scopes</option>
          {#each availableScopes as scope}
            <option value={scope.scope_id}>{scope.name}</option>
          {/each}
        </select>
      </div>
      
      <!-- Safety Impact Filter -->
      <div>
        <label for="safetyFilter" class="block text-sm font-medium text-gray-700 mb-1">Safety Impact</label>
        <select 
          id="safetyFilter"
          bind:value={selectedSafetyImpact}
          on:change={handleFilterChange}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
        >
          <option value={null}>All</option>
          <option value={SeverityLevel.LOW}>Low</option>
          <option value={SeverityLevel.MEDIUM}>Medium</option>
          <option value={SeverityLevel.HIGH}>High</option>
          <option value={SeverityLevel.CRITICAL}>Critical</option>
        </select>
      </div>
      
      <!-- Financial Impact Filter -->
      <div>
        <label for="financialFilter" class="block text-sm font-medium text-gray-700 mb-1">Financial Impact</label>
        <select 
          id="financialFilter"
          bind:value={selectedFinancialImpact}
          on:change={handleFilterChange}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
        >
          <option value={null}>All</option>
          <option value={SeverityLevel.LOW}>Low</option>
          <option value={SeverityLevel.MEDIUM}>Medium</option>
          <option value={SeverityLevel.HIGH}>High</option>
          <option value={SeverityLevel.CRITICAL}>Critical</option>
        </select>
      </div>
      
      <!-- Operational Impact Filter -->
      <div>
        <label for="operationalFilter" class="block text-sm font-medium text-gray-700 mb-1">Operational Impact</label>
        <select 
          id="operationalFilter"
          bind:value={selectedOperationalImpact}
          on:change={handleFilterChange}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
        >
          <option value={null}>All</option>
          <option value={SeverityLevel.LOW}>Low</option>
          <option value={SeverityLevel.MEDIUM}>Medium</option>
          <option value={SeverityLevel.HIGH}>High</option>
          <option value={SeverityLevel.CRITICAL}>Critical</option>
        </select>
      </div>
      
      <!-- Privacy Impact Filter -->
      <div>
        <label for="privacyFilter" class="block text-sm font-medium text-gray-700 mb-1">Privacy Impact</label>
        <select 
          id="privacyFilter"
          bind:value={selectedPrivacyImpact}
          on:change={handleFilterChange}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
        >
          <option value={null}>All</option>
          <option value={SeverityLevel.LOW}>Low</option>
          <option value={SeverityLevel.MEDIUM}>Medium</option>
          <option value={SeverityLevel.HIGH}>High</option>
          <option value={SeverityLevel.CRITICAL}>Critical</option>
        </select>
      </div>
      
      <!-- Auto-generated Filter -->
      <div class="flex items-end pb-2">
        <label class="inline-flex items-center">
          <input 
            type="checkbox" 
            bind:checked={autoGeneratedOnly}
            on:change={handleFilterChange}
            class="rounded border-gray-300 text-blue-600 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
          >
          <span class="ml-2 text-sm text-gray-700">Auto-generated only</span>
        </label>
      </div>
    </div>
  </div>
  
  <!-- Impact Rating List -->
  <div>
    {#if isLoading}
      <div class="flex justify-center items-center h-64">
        <div class="text-center">
          <RefreshCw size={36} class="animate-spin mx-auto text-primary mb-4" />
          <p class="text-gray-500">Loading impact ratings...</p>
        </div>
      </div>
    {:else if error}
      <div class="bg-red-50 border-l-4 border-red-500 p-4 mb-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <AlertTriangle class="h-5 w-5 text-red-400" />
          </div>
          <div class="ml-3">
            <p class="text-sm text-red-700">{error}</p>
          </div>
        </div>
      </div>
    {:else if scenarios.length === 0}
      <div class="text-center py-12 bg-white rounded-lg border border-gray-200">
        <Shield size={48} class="mx-auto text-gray-400 mb-4" />
        <h3 class="text-lg font-medium text-gray-900 mb-2">No impact ratings found</h3>
        <p class="text-gray-500 mb-6">There are no damage scenarios with impact ratings that match your filters.</p>
      </div>
    {:else}
      <ImpactRatingList 
        scenarios={scenarios} 
        on:edit={e => handleEditRatings(e.detail)} 
      />
    {/if}
  </div>
  
  <!-- Impact Rating Editor Dialog -->
  {#if showEditor && selectedScenario}
    <div class="fixed inset-0 backdrop-blur-sm bg-neutral-900/40 flex items-center justify-center z-50 p-4 transition-opacity duration-200">
      <div class="w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        <ImpactRatingEditor
          scenario={selectedScenario}
          on:close={handleEditorClose}
        />
      </div>
    </div>
  {/if}
</div>

<style>
  .metric-card {
    background-color: var(--color-card-bg);
    border: 1px solid var(--color-border);
    padding: 1.25rem;
    border-radius: 0.5rem;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
  }
  
  .metric-label {
    color: var(--color-text-muted);
    font-size: 0.875rem;
    margin-bottom: 0.25rem;
  }
  
  .metric-value {
    color: var(--color-text-main);
    font-size: 1.5rem;
    font-weight: 600;
  }
</style>
