"""CRA Annex VII — section body assembly.

Pure string formatting: takes the loaded value-objects and returns the
plain-text body for each of the 7 Annex VII sections.
"""
from __future__ import annotations

from typing import List, Tuple

from core.cra_annex_vii_models import (
    AnnexViiAsset,
    AnnexViiCompensatingControl,
    AnnexViiDamageScenario,
    AnnexViiRequirement,
    AnnexViiSbomEntry,
)


def section_1_body(product_name: str, product, assessment) -> str:
    parts: List[str] = [f"Product name: {product_name}"]
    if product:
        if product.product_type:
            parts.append(f"Type: {product.product_type}")
        if product.description:
            parts.append(f"Description: {product.description}")
        if product.safety_level:
            parts.append(f"Safety level: {product.safety_level}")
    if assessment.classification:
        parts.append(f"CRA classification: {assessment.classification}")
    if assessment.compliance_path:
        parts.append(f"Conformity assessment route: {assessment.compliance_path}")
    if assessment.support_period_years is not None:
        sp = f"Support period: {assessment.support_period_years} years"
        if (
            assessment.support_period_years < 5
            and assessment.support_period_justification
        ):
            sp += f" — justification: {assessment.support_period_justification}"
        parts.append(sp)
    if assessment.compliance_deadline:
        parts.append(f"Compliance deadline: {assessment.compliance_deadline}")
    return "\n".join(parts)


def section_2_body(
    requirements: Tuple[AnnexViiRequirement, ...],
    controls: Tuple[AnnexViiCompensatingControl, ...],
) -> str:
    part_ii = [r for r in requirements if r.annex_part.lower().startswith("part ii")]
    lines: List[str] = [
        "This section maps Annex II vulnerability-handling requirements to the "
        "evidence captured in QuickTARA."
    ]
    if part_ii:
        lines.append("")
        lines.append("Annex II requirement coverage:")
        for r in part_ii:
            lines.append(f"  - {r.requirement_id} ({r.name}) — status: {r.status}")
    if controls:
        lines.append("")
        lines.append("Compensating controls (Article 5(3) / Annex I §3):")
        for c in controls:
            lines.append(f"  - {c.name} [{c.status}] — {c.description}")
    return "\n".join(lines)


def section_3_body(
    assets: Tuple[AnnexViiAsset, ...],
    scenarios: Tuple[AnnexViiDamageScenario, ...],
) -> str:
    lines: List[str] = [
        "Risk assessment performed per Article 13. Source artifacts are "
        "captured in QuickTARA's TARA module and summarised below.",
        "",
        f"Assets in scope: {len(assets)}",
        f"Damage scenarios identified: {len(scenarios)}",
    ]
    if scenarios:
        threat_total = sum(s.threat_count for s in scenarios)
        lines.append(f"Linked threat scenarios: {threat_total}")
    return "\n".join(lines)


def section_4_body() -> str:
    return (
        "QuickTARA does not yet capture standards applied. "
        "List the harmonised standards or common specifications applied "
        "(e.g. EN 18031, ISO/SAE 21434), or describe the solutions adopted "
        "where they were not applied."
    )


def section_5_body(requirements: Tuple[AnnexViiRequirement, ...]) -> str:
    counts = {"compliant": 0, "partial": 0, "not_applicable": 0, "not_started": 0}
    for r in requirements:
        if r.status in counts:
            counts[r.status] += 1
    return (
        f"Conformity test evidence per Annex I (Part I + Part II). "
        f"{counts['compliant']} requirement(s) marked compliant, "
        f"{counts['partial']} partial, "
        f"{counts['not_applicable']} not applicable, "
        f"{counts['not_started']} not started. "
        "Attach test reports for every compliant or partial line."
    )


def section_6_body() -> str:
    return (
        "Attach the signed EU Declaration of Conformity. "
        "QuickTARA can pre-fill the declaration once the assessment is "
        "marked complete; it is not yet generated by this tool."
    )


def section_7_body(sboms: Tuple[AnnexViiSbomEntry, ...]) -> str:
    if not sboms:
        return (
            "No SBOM uploaded. CRA Article 13(6) requires manufacturers to "
            "identify components, including by drawing up an SBOM in a "
            "commonly used and machine-readable format."
        )
    latest = sboms[0]
    body = [
        f"Latest SBOM: {latest.sbom_format} {latest.spec_version}",
        f"Components: {latest.component_count}",
        f"Uploaded: {latest.uploaded_at.isoformat()}",
    ]
    if latest.primary_component_name:
        primary = f"Primary component: {latest.primary_component_name}"
        if latest.primary_component_version:
            primary += f" @ {latest.primary_component_version}"
        body.insert(1, primary)
    if len(sboms) > 1:
        body.append(f"({len(sboms) - 1} earlier SBOM revision(s) on file.)")
    return "\n".join(body)
