"""CRA Annex VII — Markdown renderer.

Pure formatting: takes an `AnnexViiDocument` and emits regulator-friendly
Markdown. Suitable for committing to a repo, PDF conversion via Pandoc,
or pasting into a notified-body submission portal.
"""
from __future__ import annotations

from typing import List

from core.cra_annex_vii_models import AnnexViiDocument


def render_markdown(doc: AnnexViiDocument) -> str:
    """Render the full Annex VII document as Markdown."""
    lines: List[str] = []
    lines.append(f"# CRA Annex VII — Technical Documentation: {doc.product_name}")
    lines.append("")
    lines.append(
        "_Auto-generated by QuickTARA. Source: Regulation (EU) 2024/2847, "
        "Annex VII. Sections marked **Action required** need manual input "
        "before submission to the notified body or competent authority._"
    )
    lines.append("")
    lines.append(_metadata_block(doc))
    lines.append("")
    lines.append(f"**Completeness: {doc.completeness_pct}%**")
    lines.append("")
    lines.append("---")
    lines.append("")

    for section in doc.sections:
        lines.append(f"## §{section.number} — {section.title}")
        lines.append("")
        lines.append(f"_{section.article_ref}_")
        lines.append("")
        if section.is_action_required:
            lines.append("> **Action required.** Manual input needed before submission.")
            lines.append("")
        for body_line in section.body.splitlines():
            lines.append(body_line)
        lines.append("")

    # Detailed appendices
    lines.append("---")
    lines.append("")
    lines.append("## Appendix A — Risk assessment artefacts")
    lines.append("")
    lines.append(_render_assets_table(doc))
    lines.append("")
    lines.append(_render_damage_scenarios_table(doc))
    lines.append("")

    lines.append("## Appendix B — Annex I requirement matrix")
    lines.append("")
    lines.append(_render_requirements_table(doc))
    lines.append("")

    if doc.compensating_controls:
        lines.append("## Appendix C — Compensating controls")
        lines.append("")
        lines.append(_render_controls_table(doc))
        lines.append("")

    if doc.sboms:
        lines.append("## Appendix D — Software Bill of Materials")
        lines.append("")
        lines.append(_render_sboms_table(doc))
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        f"_Generated at {doc.generated_at.isoformat()} for assessment "
        f"`{doc.assessment_id}` on product `{doc.product_id}`._"
    )
    lines.append("")
    return "\n".join(lines)


# ──────────────── Helpers ────────────────


def _metadata_block(doc: AnnexViiDocument) -> str:
    rows: List[str] = ["| Field | Value |", "| --- | --- |"]
    rows.append(f"| Product | {doc.product_name} (`{doc.product_id}`) |")
    rows.append(f"| Assessment | `{doc.assessment_id}` |")
    rows.append(f"| Classification | {doc.classification or '—'} |")
    rows.append(f"| Conformity assessment | {doc.conformity_assessment or '—'} |")
    if doc.support_period_years is not None:
        sp = f"{doc.support_period_years} years"
        if (
            doc.support_period_years < 5
            and doc.support_period_justification
        ):
            sp += f" (justification: {doc.support_period_justification})"
        rows.append(f"| Support period | {sp} |")
    else:
        rows.append("| Support period | — |")
    rows.append(f"| Compliance deadline | {doc.compliance_deadline or '—'} |")
    rows.append(f"| Safety level | {doc.safety_level or '—'} |")
    return "\n".join(rows)


def _render_assets_table(doc: AnnexViiDocument) -> str:
    if not doc.assets:
        return "_No assets recorded for this product._"
    lines = [
        "### Assets in scope",
        "",
        "| Asset | Type | C | I | A |",
        "| --- | --- | --- | --- | --- |",
    ]
    for a in doc.assets:
        lines.append(
            f"| {a.name} | {a.asset_type} | {a.confidentiality} | {a.integrity} | {a.availability} |"
        )
    return "\n".join(lines)


def _render_damage_scenarios_table(doc: AnnexViiDocument) -> str:
    if not doc.damage_scenarios:
        return "_No damage scenarios recorded for this product._"
    lines = [
        "### Damage scenarios",
        "",
        "| Scenario | Severity | S | F | O | P | Threats |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for ds in doc.damage_scenarios:
        lines.append(
            f"| {ds.name} | {ds.severity} | {ds.safety_impact} | "
            f"{ds.financial_impact} | {ds.operational_impact} | "
            f"{ds.privacy_impact} | {ds.threat_count} |"
        )
    return "\n".join(lines)


def _render_requirements_table(doc: AnnexViiDocument) -> str:
    if not doc.requirements:
        return "_No CRA requirements seeded for this assessment._"
    lines = [
        "| ID | Name | Annex part | Category | Status | Auto-mapped |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in doc.requirements:
        auto = "✓" if r.auto_mapped else "—"
        lines.append(
            f"| {r.requirement_id} | {r.name} | {r.annex_part or '—'} | "
            f"{r.category} | {r.status} | {auto} |"
        )
    return "\n".join(lines)


def _render_controls_table(doc: AnnexViiDocument) -> str:
    lines = [
        "| Control | Status | Mitigates | Description |",
        "| --- | --- | --- | --- |",
    ]
    for c in doc.compensating_controls:
        lines.append(
            f"| {c.name} | {c.status} | {c.requirement_id or '—'} | {c.description} |"
        )
    return "\n".join(lines)


def _render_sboms_table(doc: AnnexViiDocument) -> str:
    lines = [
        "| Format | Spec | Components | Primary component | Uploaded |",
        "| --- | --- | --- | --- | --- |",
    ]
    for s in doc.sboms:
        primary = s.primary_component_name or "—"
        if s.primary_component_version:
            primary += f" @ {s.primary_component_version}"
        lines.append(
            f"| {s.sbom_format} | {s.spec_version} | {s.component_count} | "
            f"{primary} | {s.uploaded_at.isoformat()} |"
        )
    return "\n".join(lines)
