"""
Report Status and Intended Use — brief statement after executive summary.
Sets expectations about draft vs. approved content.
"""
from typing import Any, Dict, List
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Spacer, Table, TableStyle


def build_report_status_section(scope_info: Dict[str, Any], config_audience: str, styles) -> List:
    try:
        heading_style = styles["CustomHeading"]
    except KeyError:
        heading_style = styles["Heading2"]

    audience_label = {
        "internal": "Internal Engineering — Full Working Document",
        "external": "External / OEM — Customer Summary Report",
        "auditor":  "Regulatory / Auditor — ISO 21434 Process Evidence",
    }.get(config_audience, config_audience.capitalize())

    status_rows = [
        [Paragraph("<b>Field</b>", styles["Normal"]), Paragraph("<b>Value</b>", styles["Normal"])],
        [Paragraph("Report type", styles["Normal"]),     Paragraph("TARA Status Report", styles["Normal"])],
        [Paragraph("Audience", styles["Normal"]),        Paragraph(audience_label, styles["Normal"])],
        [Paragraph("Document status", styles["Normal"]), Paragraph("Draft — pending engineering sign-off", styles["Normal"])],
        [Paragraph("Tool", styles["Normal"]),            Paragraph("QuickTARA — ISO/SAE 21434 TARA Platform", styles["Normal"])],
        [Paragraph("Product", styles["Normal"]),         Paragraph(scope_info.get("name", "—"), styles["Normal"])],
    ]

    table = Table(status_rows, colWidths=[2.0*inch, 4.5*inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
    ]))

    story: List = [
        Paragraph("Report Status and Intended Use", heading_style),
        Spacer(1, 6),
        table,
        Spacer(1, 8),
        Paragraph(
            "This report is a TARA status summary generated by QuickTARA. "
            "<b>Draft and candidate entries require engineering review before use as final release "
            "or regulatory compliance evidence.</b> "
            "Approved entries are marked explicitly in the risk register and treatment sections. "
            "Sections marked 'Candidate' or 'Draft' in the Assessment Status table have not yet "
            "been validated by the responsible engineering team.",
            styles["Normal"],
        ),
        Spacer(1, 12),
    ]
    return story
